version: "3.1"
services: 
  postgres:
    image: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: envidual
      POSTGRES_PASSWORD: werksstudent
      POSTGRES_DB: sportify
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped